package adapter

import (
	"database/sql"
	"fmt"
)

func CreateTables(db *sql.DB, dbName string) error {
	var query string
	switch dbName {
	case "sqlite":
		query = `
			CREATE TABLE IF NOT EXISTS messages(
				id INTEGER PRIMARY KEY AUTOINCREMENT,
				nickname TEXT NOT NULL,
				content TEXT NOT NULL,
				created_at DATETIME NOT NULL
			);

			CREATE TABLE IF NOT EXISTS admin_sessions(
				id TEXT PRIMARY KEY,
				expires_at DATETIME NOT NULL
			);
		`
	case "postgres", "postgresql":
		query = `
			CREATE TABLE IF NOT EXISTS messages (
			    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			    nickname text NOT NULL,
			    content text NOT NULL,
			    created_at timestamp NOT NULL
			);

			CREATE TABLE IF NOT EXISTS admin_sessions (
			    id text PRIMARY KEY,
			    expires_at timestamp NOT NULL
			);
		`
	default:
		return fmt.Errorf("unable to create db tables: environment variable 'DB' is invalid")
	}

	_, err := db.Exec(query)
	return err
}
