package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgxpool"
)

func CreateTables(db *pgxpool.Pool) error {
	var query string
	query = `
		CREATE TABLE IF NOT EXISTS messages (
		    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		    nickname text NOT NULL,
		    content text NOT NULL,
		    created_at timestamp NOT NULL
		);

		CREATE TABLE IF NOT EXISTS admin_sessions (
		    id text PRIMARY KEY,
		    expires_at timestamp NOT NULL
		);
	`

	_, err := db.Exec(context.Background(), query)
	return err
}
