package postgres

import (
	"database/sql"
)

func CreateTables(db *sql.DB) error {
	var query string
	query = `
		CREATE TABLE IF NOT EXISTS messages (
		    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		    nickname text NOT NULL,
		    content text NOT NULL,
		    created_at timestamp NOT NULL
		);

		CREATE TABLE IF NOT EXISTS admin_sessions (
		    id text PRIMARY KEY,
		    expires_at timestamp NOT NULL
		);
	`

	_, err := db.Exec(query)
	return err
}
