package chat

import (
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"time"

	// au "github.com/acakp/dumbchat/internal/auth"

	_ "github.com/jackc/pgx/v5/stdlib"
	"golang.org/x/crypto/bcrypt"
)

func insertMessage(db *sql.DB, msg Message) (int64, error) {
	query := `
	INSERT INTO messages (nickname, content, created_at)
	VALUES ($1, $2, $3) RETURNING id;
	`
	var msgID int
	err := db.QueryRow(
		query,
		msg.Nickname,
		msg.Content,
		msg.CreatedAt,
	).Scan(&msgID)
	if err != nil {
		return -1, err
	}
	return int64(msgID), nil
}

var ErrMessageNotFound = errors.New("Message with given ID not found")

func deleteMessage(db *sql.DB, messageID int) error {
	query := "DELETE FROM messages WHERE id = $1;"
	res, err := db.Exec(query, messageID)
	if err != nil {
		return err
	}
	if rows, _ := res.RowsAffected(); rows == 0 {
		return ErrMessageNotFound
	}
	return nil
}

func OpenDB(dbName string) (*sql.DB, error) {
	switch dbName {
	case "sqlite":
		db, err := sql.Open("sqlite", "./chat.db")
		if err != nil {
			return nil, err
		}
		db.SetMaxOpenConns(1)
		return db, nil
	case "postgres", "postgresql":
		db, err := sql.Open("pgx", getPostgresURL())
		if err != nil {
			return nil, fmt.Errorf("Unable to connect to database (postgres): %v\n", err)
		}
		return db, nil
	default:
		return nil, fmt.Errorf("Unable to connect to database: environment variable 'DB' is invalid or doesn't exist")
	}
}

func CreateTables(db *sql.DB) error {
	var query string
	if os.Getenv("DB") == "sqlite" {
		query = `
			CREATE TABLE IF NOT EXISTS messages(
				id INTEGER PRIMARY KEY AUTOINCREMENT,
				nickname TEXT NOT NULL,
				content TEXT NOT NULL,
				created_at DATETIME NOT NULL
			);

			CREATE TABLE IF NOT EXISTS admin_sessions(
				id TEXT PRIMARY KEY,
				expires_at DATETIME NOT NULL
			);
		`
	} else {
		query = `
			CREATE TABLE IF NOT EXISTS messages (
			    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			    nickname text NOT NULL,
			    content text NOT NULL,
			    created_at timestamp NOT NULL
			);

			CREATE TABLE IF NOT EXISTS admin_sessions (
			    id text PRIMARY KEY,
			    expires_at timestamp NOT NULL
			);
		`
	}

	_, err := db.Exec(query)
	return err
}

func getMessage(db *sql.DB, messageID int) (Message, error) {
	rows, err := db.Query(`
		SELECT id, nickname, content, created_at
		FROM messages WHERE id=$1;
	`, messageID)
	if err != nil {
		return Message{}, err
	}
	defer rows.Close()

	var msg Message
	for rows.Next() {
		if err := rows.Scan(&msg.ID, &msg.Nickname, &msg.Content, &msg.CreatedAt); err != nil {
			return Message{}, err
		}
	}
	return msg, nil
}

func getMessages(db *sql.DB) ([]Message, error) {
	rows, err := db.Query(`
		SELECT id, nickname, content, created_at
		FROM messages;
	`)
	if err != nil {
		return []Message{}, err
	}
	defer rows.Close()

	var messages []Message
	for rows.Next() {
		var m Message
		if err := rows.Scan(&m.ID, &m.Nickname, &m.Content, &m.CreatedAt); err != nil {
			return []Message{}, err
		}
		messages = append(messages, m)
	}
	return messages, nil
}

func newSessionID() (string, error) {
	b := make([]byte, 32)
	_, err := rand.Read(b)
	return hex.EncodeToString(b), err
}

func checkAdminPassword(db *sql.DB, pwd string) (string, error) {
	pwdHash := os.Getenv("ADMIN_PASSWORD_HASH")
	err := bcrypt.CompareHashAndPassword([]byte(pwdHash), []byte(pwd))
	if err != nil {
		return "", err
	}
	sessionID, _ := newSessionID()
	// add session id to db
	query := `
		INSERT INTO admin_sessions (id, expires_at)
		VALUES ($1, $2);
		`
	_, err = db.Exec(
		query,
		sessionID,
		time.Now().Add(10*time.Hour),
	)
	if err != nil {
		return "", err
	}
	return sessionID, nil
}

func getPostgresURL() string {
	url := fmt.Sprintf("host=%s port=%s dbname=%s user=%s password=%s sslmode=disable", os.Getenv("PGHOST"), os.Getenv("PGPORT"), os.Getenv("PGDBNAME"), os.Getenv("PGUSER"), os.Getenv("PGPASSWORD"))
	return url
}
